### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-salesforce#22]
A user reported this error:

> 2023-07-11 00:04:46.616 UTC [WARN]  steampipe-plugin-salesforce.plugin: [WARN]  1689033885946: error channel received client login error [simpleforce] Error. http code: 405 Error Message:   Error Code:

I set up a fresh account and replicated it. Debugging the simpleforce SDK, I see that it is sending a SOAP body with all the expected values:

<?xml version="1.0" encoding="utf-8" ?>
        <env:Envelope
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"
                xmlns:urn="urn:partner.soap.sforce.com">
            <env:Header>
                <urn:CallOptions>
                    <urn:client>3M...TM</urn:client>
                    <urn:defaultNamespace>sf</urn:defaultNamespace>
                </urn:CallOptions>
            </env:Header>
            <env:Body>
                <n1:login xmlns:n1="urn:partner.soap.sforce.com">
                    <n1:username>jon@jonudell.info</n1:username>
                    <n1:password>T9AL...LCv</n1:password>
                </n1:login>
            </env:Body>

And it's sending it to what I think is the right endpoint: 

> https://jonudell-dev-ed.develop.lightning.force.com/services/Soap/u/54.0

The 405 error is:

```
<body><h2>HTTP ERROR 405</h2>
<p>Problem accessing /services/Soap/u/54.0. Reason:
<pre>    Only POST allowed</pre></p><hr /><br/>
```

But the code does seem to be sending a POST?

https://github.com/simpleforce/simpleforce/blob/master/force.go#L168

**Comment by cbruno10** [comment]
@judell Can you please share your `~/.steampipe/config/salesforce.spc` with sensitive info removed?

**Comment by cbruno10** [comment]
@judell From the Slack conversation, I believe this issue has been resolved once you used the non-lightning URL, but if you're still having issues please feel free to re-open the issue. Thanks!
