### ISSUE TITLE
414 Error when making basic Salesforce Queries

### ISSUE THREAD

**Issue by keviny-ts** [turbot/steampipe-plugin-salesforce#29]
**Describe the bug**
When trying to make basic queries to some Salesforce tables, a 414 error is returned with the following message:
`ERROR: rpc error: code = Unknown desc = [simpleforce] Error. http code: 414 Error Message: Error Code: (SQLSTATE HV000)`

Here is a list of tables I am facing this issue with:
salesforce_account
salesforce_contact
salesforce_lead
salesforce_opportunity

I am making basic queries like so:
`select * from salesforce_account limit 1;`

**Steampipe version (`steampipe -v`)**
We are using the cloud version v0.20.12

**Plugin version (`steampipe plugin list`)**
Latest version (v0.5.0)

**To reproduce**
1. Create a Salesforce connection on pipes.turbot.com
2. Navigate to the query page
3. Run a query like `select * from salesforce_account limit 1;`

**Expected behavior**
One row or zero rows of data should be returned from the salesforce_account table.

**Additional context**
NA

**Comment by rajlearner17** [comment]
Slack [reference](https://turbot-community.slack.com/archives/C02NMCM2QKE/p1695684394733499)
